version: '3.2'
services:
  dbbrowser:
    container_name: dbbrowser
    image: arthurlehdermann/ubuntu-apache-php
    ports:
      - 80:80
    volumes:
      - type: bind
        source: ./
        target: /var/www/html
  dbbrowser-test-pgsql:
    container_name: dbbrowser-test-pgsql
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: dbbrowser-test
      POSTGRES_DB: dbbrowser-test-pgsql
  dbbrowser-test-mysql:
    container_name: dbbrowser-test-mysql
    image: mysql:5.7
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dbbrowser-test
      MYSQL_DATABASE: dbbrowser-test-mysql